server:
  port: 8080
  servlet:
    context-path: /api

spring:
  datasource:
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:15432/postgres
  jpa:
    hibernate:
      ddl-auto: update