server:
  servlet:
    context-path: /api

spring:
  application:
    name: siso-api
  datasource:
    username: sa
    password: password
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update

auth-service:
  authentication:
    url: https://auth-service-test.com/api
  secret-key: GmpGT97dooIJGBsknf30uhYLxveSBCFM